# Generated by Django 3.1.3 on 2021-04-12 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starter_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_assigned_to',
        ),
    ]
